[metadata]
name = smart-car-deals
version = 0.1.0
author = Mehran ESMAILYBAJEGANI
author_email = mehranesmaily907@gmail.com
description = A Python-based project that scrapes data from second-hand car sale websites to gather and visualize car listings. This tool allows users to compare prices interactively and make informed decisions when purchasing a used car.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/mehranESB/smart-car-deals.git
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Intended Audience :: Developers
    Intended Audience :: End Users/Desktop
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Internet :: WWW/HTTP :: Dynamic Content
    Topic :: Scientific/Engineering :: Visualization
    Topic :: Education :: Information Analysis
keywords = 
    car price scraper
    used car comparison
    web scraping
    data visualization
    interactive charts
    Python
    car price analysis
    second-hand car deals
    car market insights
    data-driven decisions

[options]
packages = find:
python_requires = >=3.8
install_requires =
    selenium
    arabic_reshaper
    bidi
    plotly
